name: mibancoemprendedor
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  shared_preferences: ^2.0.6
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.0.6
  flutter_map: ^0.14.0
  latlong2: ^0.8.1
  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/MiBancoEmprendedorLogo.png
